### ISSUE TITLE
Unexpected ASGI message 'http.response.start' sent, after response already completed

### ISSUE THREAD

**Issue by davidbrochart** [rexzhang/asgi-webdav#24]
I'm using [this WebDAV client](https://github.com/ezhov-evgeny/webdav-client-python-3) and I get this error with `asgi-webdav`:
```
2022-07-13 17:16:04,783 INFO: [asgi_webdav.server] ASGI WebDAV Server(v1.2.0) starting...
2022-07-13 17:16:04,783 INFO: [asgi_webdav.auth] Register User: foo, allow:[''], deny:[]
2022-07-13 17:16:04,783 INFO: [asgi_webdav.web_dav] Mapping Prefix: / => file://.
2022-07-13 17:16:04,783 INFO: [asgi_webdav.server] ASGI WebDAV Server running on http://?:? (Press CTRL+C to quit)
2022-07-13 17:16:11,997 INFO: [uvicorn.access] 127.0.0.1:59986 - "MKCOL /webdav/my_dir HTTP/1.1" 404
2022-07-13 17:16:11,997 INFO: [asgi_webdav.server] 127.0.0.1 - "MKCOL /webdav/my_dir" 409 Basic - python-requests/2.28.1
Exception in ASGI application
Traceback (most recent call last):
  File "/home/david/mambaforge/envs/jupyverse/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/david/mambaforge/envs/jupyverse/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/david/github/davidbrochart/fps/fps/app.py", line 303, in new_app
    await a(scope, receive, send)
  File "/home/david/mambaforge/envs/jupyverse/lib/python3.10/site-packages/asgi_middleware_static_file/core.py", line 66, in __call__
    await self.app(scope, receive, send)
  File "/home/david/mambaforge/envs/jupyverse/lib/python3.10/site-packages/asgi_webdav/server.py", line 65, in __call__
    await response.send_in_one_call(request)
  File "/home/david/mambaforge/envs/jupyverse/lib/python3.10/site-packages/asgi_webdav/response.py", line 138, in send_in_one_call
    await self._send_in_direct(request)
  File "/home/david/mambaforge/envs/jupyverse/lib/python3.10/site-packages/asgi_webdav/response.py", line 172, in _send_in_direct
    await request.send(
  File "/home/david/mambaforge/envs/jupyverse/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 520, in send
    raise RuntimeError(msg % message_type)
RuntimeError: Unexpected ASGI message 'http.response.start' sent, after response already completed.
```
Not sure what is going on, do you think there is a bug in the client?

**Comment by davidbrochart** [comment]
I get the same error with [this client](https://github.com/amnong/easywebdav).

**Comment by rexzhang** [comment]
Could you show me your code?

**Comment by davidbrochart** [comment]
My bad, I was still calling [other_asgi_app](https://github.com/rexzhang/asgi-webdav/blob/3766f5e4e5639e0a6eb3a732cd56675d84e8706f/examples/work_together_with_other_asgi_app.py#L42) even though the request was handled in [webdav_app](https://github.com/rexzhang/asgi-webdav/blob/3766f5e4e5639e0a6eb3a732cd56675d84e8706f/examples/work_together_with_other_asgi_app.py#L40).
Works like a charm, thanks for this great project!
